name: dbt_analytics_engineering_lab
version: '1.0.0'
config-version: 2

profile: dbt_analytics_engineering_lab

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  dbt_analytics_engineering_lab:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
