select
    order_id,
    customer_id,
    warehouse,
    order_date,
    promised_date,
    shipment_id,
    carrier,
    ship_date,
    delivery_date,
    order_line_count,
    distinct_sku_count,
    units_ordered,
    units_shipped,
    order_revenue,
    unit_fill_rate,
    is_in_full,
    calculated_on_time as is_on_time,
    is_otif,
    order_cycle_time_days,
    freight_cost,
    handling_cost,
    exception_cost,
    total_logistics_cost,
    cost_to_serve_pct,
    freight_cost_per_kg
from {{ ref('int_order_fulfillment') }}
